/** @type {import('tailwindcss').Config} */
const v = (name) => `rgb(var(--${name}) / <alpha-value>)`;
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: v('bg'),
        surface: v('surface'),
        sunk: v('sunk'),
        line: v('line'),
        ink: v('ink'),
        ink2: v('ink2'),
        ink3: v('ink3'),
        accent: v('accent'),
        'accent-soft': v('accent-soft'),
        'accent-ink': v('accent-ink'),
        pill: v('pill'),
        'pill-fg': v('pill-fg'),
        'on-accent': v('on-accent'),
        pos: v('pos'),
        warn: v('warn'),
        neg: v('neg'),
      },
      fontFamily: {
        display: ['var(--font-display)'],
        sans: ['var(--font-body)'],
      },
      borderRadius: { xl: '14px', '2xl': '20px', '3xl': '28px' },
      fontSize: {
        label: ['12px', { lineHeight: '16px', letterSpacing: '0.06em' }],
        hero: ['60px', { lineHeight: '1', letterSpacing: '-0.03em' }],
      },
      boxShadow: {
        soft: '0 1px 2px rgb(40 22 8 / 0.05), 0 8px 24px -12px rgb(40 22 8 / 0.14)',
        lift: '0 12px 40px -12px rgb(40 22 8 / 0.3)',
      },
      keyframes: {
        rise: { from: { transform: 'translateY(8px)', opacity: '0.4' }, to: { transform: 'none', opacity: '1' } },
        sheet: { from: { transform: 'translateY(100%)' }, to: { transform: 'none' } },
        fade: { from: { opacity: '0' }, to: { opacity: '1' } },
        pop: { '0%': { transform: 'scale(1)' }, '40%': { transform: 'scale(0.96)' }, '100%': { transform: 'scale(1)' } },
        scan: { '0%': { top: '4%' }, '100%': { top: '92%' } },
        nudge: { '0%, 100%': { opacity: '0.25', transform: 'translateX(0)' }, '50%': { opacity: '1', transform: 'translateX(3px)' } },
        toast: { '0%': { opacity: '0', transform: 'translateY(26px) scale(.9)' }, '60%': { opacity: '1', transform: 'translateY(-4px) scale(1.02)' }, '100%': { transform: 'none' } },
        wiggle: { '0%, 100%': { transform: 'rotate(0)' }, '25%': { transform: 'rotate(-14deg)' }, '75%': { transform: 'rotate(14deg)' } },
        boing: { '0%': { transform: 'scale(0) rotate(-20deg)' }, '55%': { transform: 'scale(1.35) rotate(8deg)' }, '80%': { transform: 'scale(.92)' }, '100%': { transform: 'none' } },
        flicker: { '0%, 100%': { transform: 'scale(1) rotate(-3deg)' }, '30%': { transform: 'scale(1.12) rotate(4deg)' }, '60%': { transform: 'scale(.96) rotate(-1deg)' } },
        grow: { from: { transform: 'scaleY(0)' }, to: { transform: 'scaleY(1)' } },
        shimmer: { '0%': { backgroundPosition: '-160% 0' }, '100%': { backgroundPosition: '260% 0' } },
        floatup: { '0%': { opacity: '0', transform: 'translateY(6px) scale(.8)' }, '18%': { opacity: '1', transform: 'translateY(0) scale(1.08)' }, '70%': { opacity: '1' }, '100%': { opacity: '0', transform: 'translateY(-34px) scale(1)' } },
        ring: { '0%': { boxShadow: '0 0 0 0 rgb(var(--accent) / .55)' }, '70%, 100%': { boxShadow: '0 0 0 14px rgb(var(--accent) / 0)' } },
        navpop: { '0%': { transform: 'scale(1)' }, '35%': { transform: 'scale(1.28) rotate(-8deg)' }, '65%': { transform: 'scale(.94) rotate(3deg)' }, '100%': { transform: 'none' } },
        squash: { '0%': { transform: 'scale(1)' }, '30%': { transform: 'scale(1.06, .94)' }, '60%': { transform: 'scale(.98, 1.03)' }, '100%': { transform: 'none' } },
        dot: { '0%, 80%, 100%': { transform: 'translateY(0)', opacity: '.35' }, '40%': { transform: 'translateY(-5px)', opacity: '1' } },
        spinin: { from: { transform: 'rotate(-90deg) scale(.6)', opacity: '0' }, to: { transform: 'none', opacity: '1' } },
      },
      animation: {
        rise: 'rise .28s cubic-bezier(.2,.8,.2,1)',
        sheet: 'sheet .32s cubic-bezier(.2,.8,.2,1)',
        fade: 'fade .2s ease-out',
        pop: 'pop .22s ease-out',
        scan: 'scan 1.1s ease-in-out infinite alternate',
        nudge: 'nudge 1.3s ease-in-out infinite',
        toast: 'toast .5s cubic-bezier(.2,.9,.3,1.2) both',
        wiggle: 'wiggle .35s ease-in-out infinite',
        boing: 'boing .6s cubic-bezier(.2,.9,.3,1.2) both',
        flicker: 'flicker 1.6s ease-in-out infinite',
        grow: 'grow .7s cubic-bezier(.2,.9,.3,1.1) both',
        shimmer: 'shimmer 2.6s ease-in-out infinite',
        floatup: 'floatup 1.5s cubic-bezier(.2,.8,.2,1) both',
        ring: 'ring 2.2s cubic-bezier(.2,.8,.2,1) infinite',
        navpop: 'navpop .5s cubic-bezier(.2,.9,.3,1.2) both',
        squash: 'squash .45s cubic-bezier(.2,.9,.3,1.2) both',
        dot: 'dot 1s ease-in-out infinite',
        spinin: 'spinin .4s cubic-bezier(.2,.9,.3,1.2) both',
      },
    },
  },
  plugins: [],
};
