import {
  Activity,
  ChartColumnIncreasing,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUpRight,
  BookOpen,
  Briefcase,
  Calendar,
  Camera,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Copy,
  CreditCard,
  Download,
  Ellipsis,
  Eye,
  EyeOff,
  HeartPulse,
  House,
  Info,
  Landmark,
  Link2,
  Lock,
  Bell,
  Palette,
  Pause,
  Pencil,
  Play,
  Plane,
  Plus,
  Receipt,
  Repeat,
  RotateCcw,
  ScanLine,
  Search,
  Send,
  Share2,
  Shield,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Split,
  Tags,
  Target,
  Ticket,
  Trash2,
  TrendingUp,
  User,
  UserPlus,
  Users,
  Utensils,
  Wallet,
  X,
  Monitor,
  Sun,
  Moon,
  IndianRupee,
  PiggyBank,
  MessageCircle,
  Zap,
  AtSign,
  Image as ImageIcon,
  ArrowRight,
  type LucideIcon,
} from 'lucide-react';

const MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  car: Car,
  bag: ShoppingBag,
  receipt: Receipt,
  ticket: Ticket,
  heart: HeartPulse,
  plane: Plane,
  repeat: Repeat,
  book: BookOpen,
  dots: Ellipsis,
  briefcase: Briefcase,
  spark: Sparkles,
  plus: Plus,
  arrows: ArrowLeftRight,
  home: House,
  activity: Activity,
  target: Target,
  user: User,
  search: Search,
  x: X,
  back: ChevronLeft,
  chevron: ChevronRight,
  down: ChevronDown,
  info: Info,
  help: CircleHelp,
  check: Check,
  trash: Trash2,
  split: Split,
  pencil: Pencil,
  pause: Pause,
  play: Play,
  camera: Camera,
  scan: ScanLine,
  calendar: Calendar,
  bell: Bell,
  shield: Shield,
  lock: Lock,
  download: Download,
  link: Link2,
  palette: Palette,
  wallet: Wallet,
  card: CreditCard,
  bank: Landmark,
  trend: TrendingUp,
  chart: ChartColumnIncreasing,
  share: Share2,
  copy: Copy,
  send: Send,
  users: Users,
  'user-plus': UserPlus,
  sliders: SlidersHorizontal,
  'arrow-out': ArrowUpRight,
  'arrow-in': ArrowDownLeft,
  eye: Eye,
  'eye-off': EyeOff,
  tags: Tags,
  reset: RotateCcw,
  monitor: Monitor,
  sun: Sun,
  moon: Moon,
  rupee: IndianRupee,
  piggy: PiggyBank,
  message: MessageCircle,
  zap: Zap,
  at: AtSign,
  image: ImageIcon,
  'arrow-right': ArrowRight,
};

export function Icon({ name, size = 18, className, strokeWidth = 1.9, label }: { name: string; size?: number; className?: string; strokeWidth?: number; label?: string }) {
  const C = MAP[name] ?? Ellipsis;
  return <C size={size} strokeWidth={strokeWidth} className={className} aria-hidden={label ? undefined : true} aria-label={label} role={label ? 'img' : undefined} />;
}
